// <auto-generated />
using System;
using Domu.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domu.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715203257_Add_CreatedAt-ExpiresAt-AcceptedAt_HouseholdInvitation")]
    partial class Add_CreatedAtExpiresAtAcceptedAt_HouseholdInvitation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domu.Api.Features.Activities.Infrastructure.HouseholdActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("ActorMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_member_id");

                    b.Property<string>("ClientApp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_app");

                    b.Property<string>("ClientPlatform")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_platform");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_version");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_household_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_household_events_occurred_at");

                    b.HasIndex("ActorId", "OccurredAt")
                        .HasDatabaseName("ix_household_events_actor_id_occurred_at");

                    b.HasIndex("ActorMemberId", "OccurredAt")
                        .HasDatabaseName("ix_household_events_actor_member_id_occurred_at");

                    b.HasIndex("HouseholdId", "OccurredAt")
                        .HasDatabaseName("ix_household_events_household_id_occurred_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_household_events_target_type_target_id");

                    b.ToTable("household_events", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("SubscriptionCancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_cancelled_at");

                    b.Property<DateTimeOffset?>("SubscriptionCurrentPeriodEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_current_period_ends_at");

                    b.Property<int>("SubscriptionPlan")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_plan");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_status");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Members.HouseholdInvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("InvitedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_member_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_household_invitations");

                    b.HasIndex("InvitedByMemberId")
                        .HasDatabaseName("ix_household_invitations_invited_by_member_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_household_invitations_token");

                    b.HasIndex("HouseholdId", "Email", "Status")
                        .HasDatabaseName("ix_household_invitations_household_id_email_status");

                    b.ToTable("household_invitations", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_household_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_household_members_user_id");

                    b.HasIndex("HouseholdId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_household_members_household_id_user_id");

                    b.ToTable("household_members", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.ShoppingLists.Infrastructure.Items.ShoppingListItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_member_id");

                    b.Property<bool>("Checked")
                        .HasColumnType("boolean")
                        .HasColumnName("checked");

                    b.Property<DateTimeOffset?>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<Guid?>("CheckedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_by_member_id");

                    b.Property<decimal?>("ContainerQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("container_quantity");

                    b.Property<string>("ContainerUnit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("container_unit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_list_id");

                    b.Property<decimal>("SortOrder")
                        .HasColumnType("numeric")
                        .HasColumnName("sort_order");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shopping_list_items");

                    b.HasIndex("AddedByMemberId")
                        .HasDatabaseName("ix_shopping_list_items_added_by_member_id");

                    b.HasIndex("CheckedByMemberId")
                        .HasDatabaseName("ix_shopping_list_items_checked_by_member_id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_shopping_list_items_household_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_shopping_list_items_item_id");

                    b.HasIndex("ShoppingListId")
                        .HasDatabaseName("ix_shopping_list_items_shopping_list_id");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("ix_shopping_list_items_space_id");

                    b.HasIndex("ShoppingListId", "Checked")
                        .HasDatabaseName("ix_shopping_list_items_shopping_list_id_checked");

                    b.HasIndex("ShoppingListId", "SortOrder")
                        .HasDatabaseName("ix_shopping_list_items_shopping_list_id_sort_order");

                    b.ToTable("shopping_list_items", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.ShoppingLists.Infrastructure.ShoppingLists.ShoppingListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_member_id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shopping_lists");

                    b.HasIndex("CreatedByMemberId")
                        .HasDatabaseName("ix_shopping_lists_created_by_member_id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_shopping_lists_household_id");

                    b.ToTable("shopping_lists", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("barcode");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("SpaceId", "Name")
                        .HasDatabaseName("ix_items_space_id_name");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcquisitionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquisition_date");

                    b.Property<int>("ContainerType")
                        .HasColumnType("integer")
                        .HasColumnName("container_type");

                    b.Property<decimal>("CurrentQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("current_quantity");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<decimal>("InitialQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("initial_quantity");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Unit")
                        .HasColumnType("integer")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_item_entries");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_entries_item_id");

                    b.ToTable("item_entries", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Spaces.SpaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_spaces");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_spaces_parent_id");

                    b.HasIndex("HouseholdId", "ParentId", "Name")
                        .HasDatabaseName("ix_spaces_household_id_parent_id_name");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Users.Infrastructure.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_identifier");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ExternalIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_identifier");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Activities.Infrastructure.HouseholdActivityEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_household_events_household_members_actor_member_id");
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Members.HouseholdInvitationEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_invitations_households_household_id");

                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("InvitedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_household_invitations_household_members_invited_by_member_id");
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_members_households_household_id");

                    b.HasOne("Domu.Api.Features.Users.Infrastructure.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_household_members_users_user_id");
                });

            modelBuilder.Entity("Domu.Api.Features.ShoppingLists.Infrastructure.Items.ShoppingListItemEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("AddedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_items_household_members_added_by_member_id");

                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("CheckedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_shopping_list_items_household_members_checked_by_member_id");

                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_items_households_household_id");

                    b.HasOne("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_shopping_list_items_items_item_id");

                    b.HasOne("Domu.Api.Features.ShoppingLists.Infrastructure.ShoppingLists.ShoppingListEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_list_items_shopping_lists_shopping_list_id");

                    b.HasOne("Domu.Api.Features.Spaces.Infrastructure.Spaces.SpaceEntity", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_shopping_list_items_spaces_space_id");
                });

            modelBuilder.Entity("Domu.Api.Features.ShoppingLists.Infrastructure.ShoppingLists.ShoppingListEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_lists_household_members_created_by_member_id");

                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_lists_households_household_id");
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntryEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_entries_items_item_id");
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Spaces.SpaceEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_households_household_id");

                    b.HasOne("Domu.Api.Features.Spaces.Infrastructure.Spaces.SpaceEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_spaces_spaces_parent_id");
                });

            modelBuilder.Entity("Domu.Api.Features.ShoppingLists.Infrastructure.ShoppingLists.ShoppingListEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntity", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
