// <auto-generated />
using System;
using Domu.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domu.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("SubscriptionCancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_cancelled_at");

                    b.Property<DateTimeOffset?>("SubscriptionCurrentPeriodEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_current_period_ends_at");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subscription_plan");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subscription_status");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.HasIndex("OwnerId", "Name")
                        .HasDatabaseName("ix_households_owner_id_name");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Members.HouseholdInvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_household_invitations");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_household_invitations_invited_by_user_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_household_invitations_token");

                    b.HasIndex("HouseholdId", "Email", "Status")
                        .HasDatabaseName("ix_household_invitations_household_id_email_status");

                    b.ToTable("household_invitations", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_household_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_household_members_user_id");

                    b.HasIndex("HouseholdId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_household_members_household_id_user_id");

                    b.ToTable("household_members", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("barcode");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("SpaceId", "Name")
                        .HasDatabaseName("ix_items_space_id_name");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcquisitionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquisition_date");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_item_entries");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_entries_item_id");

                    b.ToTable("item_entries", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Spaces.SpaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_spaces");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_spaces_parent_id");

                    b.HasIndex("HouseholdId", "ParentId", "Name")
                        .HasDatabaseName("ix_spaces_household_id_parent_id_name");

                    b.ToTable("spaces", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Users.Infrastructure.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_identifier");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ExternalIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_identifier");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Members.HouseholdInvitationEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_invitations_households_household_id");

                    b.HasOne("Domu.Api.Features.Users.Infrastructure.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_household_invitations_users_invited_by_user_id");
                });

            modelBuilder.Entity("Domu.Api.Features.Households.Infrastructure.Members.HouseholdMemberEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_members_households_household_id");

                    b.HasOne("Domu.Api.Features.Users.Infrastructure.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_members_users_user_id");
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntryEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_entries_items_item_id");
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Spaces.SpaceEntity", b =>
                {
                    b.HasOne("Domu.Api.Features.Households.Infrastructure.Households.HouseholdEntity", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_spaces_households_household_id");

                    b.HasOne("Domu.Api.Features.Spaces.Infrastructure.Spaces.SpaceEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_spaces_spaces_parent_id");
                });

            modelBuilder.Entity("Domu.Api.Features.Spaces.Infrastructure.Items.ItemEntity", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
